[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/pne-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false
license = "Apache-2.0"

[workspace.dependencies]
pne-core = { path = "crates/pne-core" }
pne-perf = { path = "crates/pne-perf" }
pne-energy = { path = "crates/pne-energy" }

[workspace.lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_op_in_unsafe_fn = "deny"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
undocumented_unsafe_blocks = "warn"
