[package]
name = "pne-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[[bin]]
name = "pne-profiler"
path = "src/main.rs"

[dependencies]
pne-core.workspace = true
pne-perf.workspace = true
pne-energy.workspace = true
clap = { version = "4.6.7", features = ["derive"] }

[lints]
workspace = true
